NAMEooooo		= replace
CXX			= c++
CXXFLAGS	= -Wall -Wextra -Werror -std=c++98 -pedantic
SRCS		= main.cpp
OBJS		= $(SRCS:.cpp=.o)
HEADERS		= 
all: $(NAMEooooo)

$(NAMEooooo): $(OBJS)
	$(CXX) $(CXXFLAGS) $(OBJS) -o $(NAMEooooo)

%.o: %.cpp $(HEADERS)
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS)

fclean:
	rm -f $(OBJS) $(NAMEooooo)
re: fclean all
.PHONY: all clean fclean re
